apiVersion: v1
kind: ConfigMap
metadata:
  name: triplogs-backend-config
  namespace: default
data:
  # Modo de execução
  MODE: "PRODUCTION"
  # Debug (desativado em produção)
  DEBUG: "False"
  # IP local (use o serviço interno do Kubernetes)
  MY_IP: "0.0.0.0"
  # Hosts permitidos
  ALLOWED_HOSTS: "triplogs-backend-service"
  # CORS - permitir o frontend
  CORS_ALLOWED_ORIGINS: "*"
