apiVersion: v1
kind: ConfigMap
metadata:
  name: triplogs-backend-config
  namespace: triplogs-prod
data:
  # Modo de execução
  MODE: "PRODUCTION"
  # Debug (desativado em produção)
  DEBUG: "False"
  # IP local (use o serviço interno do Kubernetes)
  MY_IP: "0.0.0.0"
  # Hosts permitidos
  ALLOWED_HOSTS: "*.triplogs.com,backend.triplogs.com,triplogs-backend-service.triplogs-prod.svc.cluster.local"
  # CORS - permitir o frontend
  CORS_ALLOWED_ORIGINS: "http://frontend.triplogs.com,https://frontend.triplogs.com,http://triplogs-frontend-service.triplogs-prod.svc.cluster.local"
