apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

images:
  - name: ghcr.io/gabriel04alves/triplogs-backend
    newName: ghcr.io/gabriel04alves/triplogs-backend
    newTag: 6a570d05ed198d4779efb470fe9eefa206ada51b
