apiVersion: v1
kind: Service
metadata:
  name: triplogs-backend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: triplogs-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
