apiVersion: apps/v1
kind: Deployment
metadata:
  name: triplogs-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triplogs-frontend
  template:
    metadata:
      labels:
        app: triplogs-frontend
    spec:
      containers:
        - name: triplogs-frontend
          image: ghcr.io/gabriel04alves/triplogs-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
