apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/gabriel04alves/triplogs-frontend
  newName: ghcr.io/gabriel04alves/triplogs-frontend
  newTag: 88be6a2d55e7a899a12f86079ea78a5b38a1c423
