apiVersion: v1
kind: Service
metadata:
  name: triplogs-frontend-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: triplogs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
